services:
  - type: web
    name: the-riddle-app
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bin/rails server -b 0.0.0.0 -p $PORT"
    healthCheckPath: /up
    envVars:
      - key: RAILS_ENV
        value: production
      - key: SOLID_QUEUE_IN_PUMA
        value: "true"
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "0"
      - key: RAILS_MAX_THREADS
        value: "3"
      - key: MALLOC_ARENA_MAX
        value: "2"
      - key: DATABASE_URL
        sync: false
      - key: PREPEND_TOKEN_OPENAI
        sync: false
      - key: RAILS_LOG_LEVEL
        value: info
